Set variables "convert" and "archive" in TUI
larnaa/bluecoins-cli pull request #23
Opened 2022-10-20 20:33 UTC by larnaa

Close #22

2022-10-20 20:56 UTC, droserasprout commented on src/bluecoins_cli/adb.py
> +    def cli_command_run(self, cli_command: str, db: str, keys: str) -> None:
I suggest renaming keys -> options/arguments.

See [argparse tutorial](https://docs.python.org/3/howto/argparse.html) to learn the difference.

2022-10-20 20:59 UTC, droserasprout commented on src/bluecoins_cli/adb.py
> +def execute_cli_command_with_adb(cli_command: str, activity: str, keys_value: str = '') -> None:
It's unobvious what's `activity` argument purpose (to start after the final sync is complete). Also, optional?

2022-10-26 14:45 UTC, larnaa commented
@droserasprout It's working, but don't use it on the prod base.

2022-10-27 17:26 UTC, droserasprout requested changes

2022-10-27 17:26 UTC, droserasprout commented on pyproject.toml
>  [tool.poetry.dev-dependencies]
Rename to `[tool.poetry.group.dev.dependencies]`

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/adb.py
> -    def cli_command_run(self, cli_command: str, db: str) -> None:
Unused function

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/cli.py
> +# sync = SyncManager()
Cleanup please

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/cli.py
> +@root.group(help='Start CLI')
Maybe something like "Commands to manage database lalala"?

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/cli.py
> +    db: str,
No such option in click decorators.

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/sync_manager.py
> +    """
Docstrings must be placed right after class/def

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/sync_manager.py
> +device = Device.connect()
A side effect, unexpected actions on module import

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/tui.py
> +sync = SyncManager()
Side effect, see comment in sync_manager module.

2022-10-27 17:26 UTC, droserasprout commented on src/bluecoins_cli/tui.py
> +    path_test = '/home/larnaa/VScode_project/bluecoins-cli/Bluecoins_last_3.fydb'
I don't think we should merge it. Hardcode is okay for now, but not machine-specific.

2022-10-28 17:51 UTC, droserasprout approved these changes

2022-10-28 17:58 UTC, merged